# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Countinuous Integration

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build with dotnet
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
      working-directory: Eva.WorkingLibrary.Publish
    - name: Test
      run: dotnet test
      working-directory: Eva.WorkingLibrary.Publish
    - name: Run unit test
      run: Eva.UnitTest.xUnit
